steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pavigodj/playwright_gcloud.git', '/workspace/your-repo']
    id: 'Clone Repository'

  # Step 2: Build Docker Image
  - name: 'gcr.io/docker-docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/your-image-name', 
      '/workspace/your-repo'
    ]
    id: 'Build Docker Image'

  # Step 3: Run pytest inside the Docker container
  - name: 'gcr.io/$PROJECT_ID/your-image-name'  # Use the image built in the previous step
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pytest --alluredir=/workspace/allure-results
    id: 'Run Tests with Allure'

  # Step 4: Generate Allure Report
  - name: 'frankescobar/allure-docker-service'  # Using Allure Docker service to generate report
    args: [
      'generate', 
      '/workspace/allure-results',
      '-o', 
      '/workspace/allure-report'
    ]
    id: 'Generate Allure Report'

  # Step 5: Upload Allure Report to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      '-m', 'cp', '-r',
      '/workspace/allure-report',
      'gs://your-bucket-name/allure-reports'
    ]
    id: 'Upload Allure Report to GCS'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Optional: Choose a machine type for the build

substitutions:
  _BUCKET_NAME: 'playwright_logs'  # Replace with your GCS bucket name

timeout: '900s'

