steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pavigodj/playwright_gcloud.git', '/workspace/repo']
    id: 'Clone Repository'

  # Step 2: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/playwright',
      '/workspace/repo'
    ]
    id: 'Build Docker Image'

  # Step 3: Run pytest inside the Docker container
  - name: 'gcr.io/$PROJECT_ID/playwright'  # Use the image built in the previous step
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pytest --html=/workspace/test-reports/report.html
    id: 'Run Tests with HTML Reporting'

  # Step 4: Generate HTML Report to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/test-reports'
      - 'gs://playwright_logs/test-reports'
    id: 'Upload HTML Report to GCS'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Optional: Choose a machine type for the build

substitutions:
  _BUCKET_NAME: 'playwright_logs'  # Replace with your GCS bucket name

timeout: '900s'

